stages:
    - testing
    
    
Testing:
    stage: testing
    image: node:latest
    before_script:
        # ENV is exported as a path to your "ENV" file, 
        # this is copying it to a local '.env' file
        - cp $ENV .env
        # If you need it, this is a way to export the
        # environment variables inside your file
        - source .env; export $(cut -d= -f1 .env);
        # Debugging the pipelines
        - ls -lah
        # Your old commands
        - npm install --no-optional
    script:
        - npm run test
